#!/usr/bin/env bash
#
# Startup script for psdash.

# To get the service to restart correctly on reboot, uncomment below (3 lines):
# ========================
# chkconfig: 3 99 99
# description: psdash
# processname: psdash
# ========================

# Source function library.
. /etc/init.d/functions

usage()
{
    echo "Usage: ${0##*/} [-d] {start|stop|restart} [ CONFIGS ... ] "
    exit 1
}

[ $# -gt 0 ] || usage

##################################################
# Some utility functions
##################################################

PSDASH_USER=psdash

PROG=psdash
LOGS="/var/log/aeromock/aeromock.log"
CMD="psdash --log $LOGS"
PIDFILE=/var/run/$PROG.pid

start() {
  echo -n $"Starting $PROG: "

  if [ -f $PIDFILE ]; then
    PID=`cat $PIDFILE`
    PID_CHECK=`ps ax | cut -d" " -f2 | grep $PID`
    if [ ! -z $PID_CHECK ]; then
      failure $"Already Running"
      return 1
    fi
  fi

  daemon --user $PSDASH_USER --pidfile $PIDFILE $CMD > /dev/null 2>&1 &
  RETVAL=$?
  sleep 3

  PID=`ps ax | grep python | grep psdash | cut -d" " -f2`

  echo
  [ $RETVAL -ne 0 ] && failure
  [ $RETVAL -eq 0 ] && echo $PID > $PIDFILE && success
  return $RETVAL
}

stop() {
  echo -n $"Stopping $PROG: "

  killproc -p $PIDFILE $PROG
  RETVAL=$?
  echo
  [ $RETVAL -ne 0 ] && failure
  [ $RETVAL -eq 0 ] && success
  return $RETVAL
}


ACTION=$@
case "$ACTION" in
  start)
    start
    ;;

  stop)
    stop
    ;;

  restart)
    stop "$@"
    start "$@"
    ;;
  *)
    usage
esac

exit $?
